site_name: Summaries 4G
site_url: https://summaries-4g.netlify.app
copyright: "Copyright &copy; 2025 Victor Spârleanu (<a href=\"/LICENSE/\" style=\"text-decoration: underline; font-style: italic;\">license</a>)"  # Displayed in the footer

# Include extra CSS stylesheet
extra_css:
  - stylesheets/extra.css

# Include extra JS modules for added functionality
extra_javascript:
  - javascripts/mathjax.js # Enable MathJax for LaTex
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # Required for MathJax

extra:
  analytics:
    provider: google
    property: G-GJH1475WEJ
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/VSparl/summary-site
      name: Behind the scenes on GitHub

# Configure Markdown extensions for added functionality
markdown_extensions:
  - tables # Add support for tables
  - footnotes # Add footnote support
  - admonition # Pretty boxes that show important information
  - pymdownx.details # Make admonitions collapsible
  - pymdownx.superfences: # Enable nesting of elements (like code blocks in quotes)
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex: # Required for MathJax
      generic: true
  - pymdownx.caret # Enable ^superscript^
  - pymdownx.tilde # Enable ~subscript~
  - pymdownx.mark # Enable ==highlighting==, ~~strikethrough~~ and ^^underline^^
  - toc:
      permalink_title: Permalink to this chapter  # what will be displayed when hovering over the permalink icon
      permalink: ⚓︎  # This icon will be displayed next to titles to make a permalink to the section
      toc_depth: 3

# Configure the color scheme and features
theme:
  name: material # Use the Material for MkDocs theme
  palette:
    scheme: slate # Dark mode
    primary: custom # Use primary color defined in extra.css
  font:
    text: Raleway
    code: JetBrains Mono
  features:
    - header.autohide  # Autohide header when scrolling
  icon:
    admonition:  # Configure the icons for admonitions by name
      summary: octicons/note-16

  features:
    - search.suggest  # Search suggestions
    - search.share  # Quick copy of search query with results
    - navigation.instant # Quick navigation
    - navigation.instant.progress # Show page load progress
    - navigation.tabs # Show tabs in title bar
    - navigation.top # Show back to top button
    - navigation.path # Show path breadcrumbs at top of file

plugins:
- search

# Website navigation structure
nav:
  - Home: index.md
  - About: about.md
  - Biology:
      - Welcome: bi/index.md
      - "1 - Nervous System": bi/1/summary.md
  - Chemistry:
      - Welcome: ci/index.md
      - "1 - Ladungswolken und Moleküle": ci/1/summary.md
      - "2 - Organische Stoffe, zwischenmolekulare WW, Strahlung": ci/2/summary.md
  - Economics & Law:
      - Welcome: wr/index.md
      - "1 - Introduction": wr/1/summary.md
      - "2 - Law": wr/2/summary.md
      - "3 - Economics": wr/3/summary.md
  - Geography:
      - Welcome: gg/index.md
      - "1 - Amerika": gg/1/summary.md
      - "2 - Naturgefahren in Nordamerika": gg/2/summary.md
  - History:
      - Welcome: gs/index.md
      - "1 - USA": gs/1/summary.md
  - Informatics:
      - Welcome: in/index.md
  - Math:
      - Welcome: bma/index.md
      - "1 - Trigonometry and Logarithms": bma/1/summary.md
  - Applied Math:
      - Welcome: sam/index.md
