site_name: Summaries 4G
site_url: https://summaries-4g.netlify.app

# Include extra CSS stylesheet
extra_css:
  - stylesheets/extra.css

# Configure the color scheme and features
theme:
  name: material # Use the Material for MkDocs theme
  palette:
    scheme: slate # Dark mode
    primary: custom # Use primary color defined in extra.css

  features:
    - navigation.instant # Quick navigation
    - navigation.instant.progress # Show page load progress
    - navigation.tabs # Show tabs in title bar
    - navigation.top # Show back to top button
    - navigation.path # Show path breadcrumbs at top of file

markdown_extensions:
  - admonition # Pretty boxes that show important information
  - pymdownx.details # Make admonitions collapsible
  - pymdownx.superfences # Enable nesting of elements (like code blocks in quotes)

# Website navigation structure
nav:
  - Home: index.md
  - About: about.md
  - Math:
      - Welcome: bma/index.md
      - "1 - Trigonometry and Logarithms": bma/1/summary.md
      - "60 - Advanced quantum mechanics interfering with sub-atomic particles on the andromeda galaxy": bma/60/summary.md
  - Applied Math:
      - Welcome: sam/index.md
  - Economics & Law:
      - Welcome: wr/index.md
  - Informatics:
      - Welcome: in/index.md
  - Biology:
      - Welcome: bi/index.md
  - Geography:
      - Welcome: gg/index.md
  - Physics:
      - Welcome: py/index.md
  - Chemistry:
      - Welcome: ci/index.md
  - History:
      - Welcome: gs/index.md
