site_name: Summaries 4G
site_url: https://summaries-4g.netlify.app

# Include extra CSS stylesheet
extra_css:
  - stylesheets/extra.css

# Include extra JS modules for added functionality
extra_javascript:
  - javascripts/mathjax.js # Enable MathJax for LaTex
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # Required for MathJax

# Configure Markdown extensions for added functionality
markdown_extensions:
  - tables # Add support for tables
  - admonition # Pretty boxes that show important information
  - pymdownx.details # Make admonitions collapsible
  - pymdownx.superfences # Enable nesting of elements (like code blocks in quotes)
  - pymdownx.arithmatex: # Required for MathJax
      generic: true
  - pymdownx.caret # Enable ^superscript^
  - pymdownx.tilde # Enable ~subscript~
  - pymdownx.mark # Enable ==highlighting==, ~~strikethrough~~ and ^^underline^^

# Configure the color scheme and features
theme:
  name: material # Use the Material for MkDocs theme
  palette:
    scheme: slate # Dark mode
    primary: custom # Use primary color defined in extra.css

  features:
    - navigation.instant # Quick navigation
    - navigation.instant.progress # Show page load progress
    - navigation.tabs # Show tabs in title bar
    - navigation.top # Show back to top button
    - navigation.path # Show path breadcrumbs at top of file

# Website navigation structure
nav:
  - Home: index.md
  - About: about.md
  - Biology:
      - Welcome: bi/index.md
  - Chemistry:
      - Welcome: ci/index.md
  - Economics & Law:
      - Welcome: wr/index.md
      - "1 - Introduction": wr/1/summary.md
  - Geography:
      - Welcome: gg/index.md
      - "1 - Amerika": gg/1/summary.md
  - History:
      - Welcome: gs/index.md
  - Informatics:
      - Welcome: in/index.md
  - Math:
      - Welcome: bma/index.md
      - "1 - Trigonometry and Logarithms": bma/1/summary.md
  - Applied Math:
      - Welcome: sam/index.md
  - Physics:
      - Welcome: py/index.md
