site_name: Summaries 4G
site_url: https://summaries-4g.netlify.app
theme:
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.top
    - navigation.path
  name: material
  palette:
    scheme: slate
    primary: custom
extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - About: about.md
  - Math: bma/index.md
  - Applied Math: sam/index.md
  - Economics & Law: wr/index.md
  - Informatics: in/index.md
  - Biology: bi/index.md
  - Geography: gg/index.md
  - Physics: py/index.md
  - Chemistry: ci/index.md
  - History: gs/index.md
